### ISSUE TITLE
food price not being displayed on prereg page

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#20]
![image](https://cloud.githubusercontent.com/assets/5413064/14858808/7e22fccc-0c6f-11e6-80eb-22060c4e4055.png)

says
"Pay an extra $ for food"

probably means to say:
"Pay an extra $20 for food"

**Comment by binary1230** [comment]
code says ```Pay an extra <b>${{ c.FOOD_PRICE }}</b> for food```

**Comment by binary1230** [comment]
also, this behavior is causing Attendee.total_cost to puke:

```python
Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 179, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 170, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 194, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 278, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 240, in with_rendering
    result = func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 23, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 27, in with_check
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 126, in form
    message = check(attendee, prereg=True)
  File "/usr/local/uber/plugins/uber/uber/utils.py", line 75, in check
    message = validator(model)
  File "/usr/local/uber/plugins/uber/uber/model_checks.py", line 106, in total_cost_over_paid
    if attendee.total_cost < attendee.amount_paid:
  File "/usr/local/uber/plugins/uber/uber/models.py", line 328, in __getattr__
    raise AttributeError(self.__class__.__name__ + '.' + name)
AttributeError: Attendee.total_cost```
