### ISSUE TITLE
missing check_prereg_reqs() on transferring badge

### ISSUE THREAD

**Issue by bds002** [magfest/magstock#36]
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 179, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 170, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 194, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 278, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 240, in with_rendering
    result = func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 23, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 390, in transfer_badge
    message = check(attendee) or check_prereg_reqs(attendee)
NameError: name 'check_prereg_reqs' is not defined

**Comment by binary1230** [comment]
so ok really weird, this seems like it WAS changed in this PR here:
https://github.com/magfest/ubersystem/pull/1566/files#diff-9c3818f655c258e1b711348de8f069c9R399

And using 'git blame' it acts like it wasn't changed, maybe it was reverted or something later.  Investigating.

In any case I think the fix for this is to change in ```transfer_badge()``` this:
```message = check(attendee) or check_prereg_reqs(attendee)```
to this:
```message = check(attendee, prereg=True)```

**Comment by binary1230** [comment]
looks like it was reintroduced during a change made here, probably unfortunate timing between merges or an improper merge.
https://github.com/magfest/ubersystem/commit/fe4266d24ebe1844c59260ded8175c4941a8c7cc#diff-9c3818f655c258e1b711348de8f069c9R400
